### ISSUE TITLE
Provenance Codes

### ISSUE THREAD

**Issue by cbizon** [tnavatar/clingen-data-model#102]
If anybody can explain to me why 

Provenance.agent.type is a Coding
and 
Provenance.entity.type is a Coding

but
Provenance.agent.role is a code 
and
Provenance.entity.role is a Coding

and

Provenance.reason is a CodeableConcept

I will send them a dollar.

**Comment by srynobio** [comment]
_if I had to guess:_

Provenance.reason: _one or more terminologies or ontologies, but may also be defined by the provision of text_ i.e. SNOMED term, etc.

From the FHIR [provenance](http://www.hl7.org/FHIR/provenance-definitions.html) page it looks like agent.role/type are both coding. 

I agree that Provenance.entity.role is a bit strange, and if I had to guess as to why it's using code and not coding is because of how it's [defined](http://www.hl7.org/FHIR/terminologies.html).  In Provenance.reason, you want the code (SNOMED:ID) and the system (SNOMED), where Provenance.entity.role would be a code defined by Provenance.entity.

**Comment by larrybabb** [comment]
I want a dollar!  So, maybe this will help

Excerpts from 
http://www.hl7.org/implement/standards/fhir/2015May/terminologies.html

code 
http://www.hl7.org/implement/standards/fhir/2015May/datatypes.html#code
The instance represents the code only. The system is implicit - it is
defined as part of the definition of the element, and not carried in the
instance.  
Coding 
http://www.hl7.org/implement/standards/fhir/2015May/datatypes.html#Coding
A data type that has a code and a system element that identifies where the
definition of the code comes from
CodeableConcept 
<http://www.hl7.org/implement/standards/fhir/2015May/datatypes.html#Codeable
Concept> A type that represents a concept by plain text and/or one or more
Codings

"In FHIR, Code Pairs are always represented as "code" and "system", except
for the simple data type "code"
http://www.hl7.org/implement/standards/fhir/2015May/datatypes.html#code
data type where the namespace (e.g. the system element/property) is fixed in
the schema and not represented explicitly."

So, a code is something that is built into FHIR (no namespace needed). Like
enums in an application.
Coding is a single code defined within a namespace (by an authority).  These
can be used in a a controlled value set if desired.
CodeableConcept is the ability to specify multiple Codings, which are
potentially semantically equivalent (at least from the senders perspective).
This is used to assist the digester by providing greater opportunity for the
digester to understand at least one of the providing Codings in their own
context.  It also, allows from a simple freeform text description, if one
exists and if there are no Codings (code-system pairs) available.

Why do they apply them as they do in Provenance?  Tough questions.

It is generally a control thing.  The CodeableConcept is the most flexible
for the implementer.  As you go down the list it gets more rigid and as such
should be used only when it makes explicit sense to be rigid.

In the end, this may be a result of the fact that this has not been well
vetted in the FHIR spec to date.  We (I) should post this question to FHIR.
If I do, will I still get the $1?

From:  cbizon notifications@github.com
Reply-To:  tnavatar/clingen-data-model
<reply+000ea21b908d2f41a30518030c41e0698b9b1f4a99fde36e92cf0000000111565a2f9
2a169ce04414c62@reply.github.com>
Date:  Monday, April 27, 2015 4:12 PM
To:  tnavatar/clingen-data-model clingen-data-model@noreply.github.com
Subject:  [clingen-data-model] Provenance Codes (#102)

If anybody can explain to me why

Provenance.agent.type is a Coding
and 
Provenance.entity.type is a Coding

but
Provenance.agent.role is a code
and
Provenance.entity.role is a Coding

and

Provenance.reason is a CodeableConcept

I will send them a dollar.


Reply to this email directly or view it on GitHub
https://github.com/tnavatar/clingen-data-model/issues/102 .

**Comment by cbizon** [comment]
Thanks for the comments!

Shawn: Where did you find the bit about reason / SNOMED terms?  I agree that wanting to use SNOMED would make reason a good candidate for CodableConcept.

On entity.role / agent.role being code / Coding, you are right, my message swapped those (but I still don't get it).

Larry: Yeah, I (think) I understand the difference between the three (or at least I know where to go to remind myself of the difference), but what is it that makes one role a code and another a Coding?  It's not clear to me.  

So yeah, getting clarification from FHIR would be worth a buck to me! (or even a beer)

**Comment by srynobio** [comment]
From [this](http://www.hl7.org/FHIR/terminologies.html) page, fourth bulletin.

**Comment by larrybabb** [comment]
As an FYI for anyone that may want to track/submit issues to FHIR, you can
go here http://gforge.hl7.org/gf/project/fhir and do it. You will need to
create an account, but I do believe anyone can post issues or ask for
clarifications here.  If not, pass them on to me and I will do so.

I have entered tracker #6210 to request clarification of why the
ProvenanceEntityRole is not type Coding like the AgentType, AgentRole and
EntityType attributes.

I'll share the result when it becomes available.

From:  Shawn Rynearson notifications@github.com
Reply-To:  tnavatar/clingen-data-model
<reply+000ea21b9f0f193f8e82f5400ec30e0cbbe2dbf9b35d5f0f92cf0000000111574a509
2a169ce04414c62@reply.github.com>
Date:  Tuesday, April 28, 2015 9:17 AM
To:  tnavatar/clingen-data-model clingen-data-model@noreply.github.com
Cc:  Lawrence Babb larry.babb@gmail.com
Subject:  Re: [clingen-data-model] Provenance Codes (#102)

From this http://www.hl7.org/FHIR/terminologies.html  page, fourth
bulletin.


Reply to this email directly or view it on GitHub
<https://github.com/tnavatar/clingen-data-model/issues/102#issuecomment-9705
7739> .

**Comment by larrybabb** [comment]
I received an answer to the FHIR HL7GForge issue I posted from above.

My question was:
I've been asked by others why ProvenanceAgentRole, ProvenanceAgentType and ProvenanceEntityType are defined as Coding and ProvenanceEntityRole is defined as code.  

It is not obvious to me why this distinction is made.  Could someone clarify?

The answer I received is:
Make Provenance.agent.type a field of type 'code'. Policy is that you use Coding when the value set binding is 'extensible', and code when the value set binding is 'required'.

**Comment by bpow** [comment]
Thanks for looking into this @larrybabb, but I think that is only a half-answer to the question (and only answers the part that I think @cbizon already understands...)

The natural extension to the question (and I think what @cbizon was asking to begin with) is: Why is Provenence.agent.role not extensible while the other similar attributes are extensible?

**Comment by larrybabb** [comment]
I will forward the clarified follow-up question to the FHIR gods.
