### ISSUE TITLE
intronOffsetGenomicCoordinate

### ISSUE THREAD

**Issue by ronakypatel** [tnavatar/clingen-data-model#108]
To create simple allele for intronic region, one needs to define intronOffsetGenomicCoordinate, which looks good. Just to make sure this genomic coordinate (reference+coordinate+allele) will be used to create different simple allele, right? 

The intronic allele defined with respect to transcript which has genomic coordinates and a different simple allele defined with respect to genomic reference will be part of the same canonical allele. This looks little redundant but want to make sure my understanding is right.

**Comment by larrybabb** [comment]
In the examples, we do have a several Simple alleles tied to the canonical allele which includes the intronic simple allele representation.  The simple alleles in this group include...
- one for the intronic version based on the NM_ reference sequence that has an intronOffsetGenomicCoordinate that references the NC_ reference sequence. 
- two others for the build 37 as well as the build 38 genomic alleles based on the corresponding versions of the NC_ reference sequences for each build.

To be clear, there is no requirement that the intronOffsetGenomicCoordinate data (start, end, referenceSeq) be explicitly used in a separate SimpleAllele, however, it does make sense that it would occur most of the time, since the genomic reference is itself a standalone simple allele too.

I suppose if someone was to define an intron simple allele and base the intronOffsetGenomicCoordinate on a genomic reference sequence that was not also used explicitly in a genomic simple allele it would not  be wrong.  It would be more likely observed to be missing as another obvious form of the canonical allele's set of simple alleles.

I hope that is helpful.

**Comment by larrybabb** [comment]
Ronak, please confirm whether or not you have a satisfactory answer.  If so, please close this otherwise let's discuss at the next meeting.
