### ISSUE TITLE
What does it mean for a resource to have a 'control' value

### ISSUE THREAD

**Issue by bpow** [tnavatar/clingen-data-model#113]
This probably mostly a question for @larrybabb to answer with his FHIR-knowledge.

The documentation which you have styled after FHIR appears to use "Control" to relate cardinality (I have not looked at enough of the examples to see if there are any resources or attributes that have anything other than a cardinality in that field).

However, in the resource documentation you created, as well as in the FHIR resource definitions (e.g. for [Patient](https://www.hl7.org/fhir/patient-definitions.html), not only the attributes of the resources but the resources themselves also have "Control" values, and the "Control" value for a resource itself is always '1..1' (again, as far as I saw, and I cannot imagine how it would be anything else).

I'm not coming up with a good way to ask this, possibly because I am so confused as to why documention of a resource should relate the cardinality of that resource-- it should only have a cardinality in the context of being linked to as (part of) an attribute from another resource.

Does my confusion make sense?

**Comment by larrybabb** [comment]
I'm right there with you.  I think this is an artifact of their automated
build from meta data about the Resource.  I'm guessing that it was easier to
just fill in "1..1" on the top level resource's Control value then to hide
it.  I suppose you could say that the Resource always has to exist when you
are referring to an instance of it, but I get your point and your confusion
on the issue.

I could make a suggestion to the FHIR guys to see if they will change the
doc to hide the Control value at the top level Resource detailed
description.

Let me know if you would like me to do that or not.

Larry

From:  Bradford Powell notifications@github.com
Reply-To:  tnavatar/clingen-data-model
<reply+000ea21b1e5f4647558ac4c3d8715d42aee7a4c51314edf792cf00000001116dfe379
2a169ce04941cc7@reply.github.com>
Date:  Friday, May 15, 2015 2:34 PM
To:  tnavatar/clingen-data-model clingen-data-model@noreply.github.com
Cc:  Lawrence Babb larry.babb@gmail.com
Subject:  [clingen-data-model] What does it mean for a resource to have a
'control' value (#113)

This probably mostly a question for @larrybabb
https://github.com/larrybabb  to answer with his FHIR-knowledge.

The documentation which you have styled after FHIR appears to use "Control"
to relate cardinality (I have not looked at enough of the examples to see if
there are any resources or attributes that have anything other than a
cardinality in that field).

However, in the resource documentation you created, as well as in the FHIR
resource definitions (e.g. for Patient
https://www.hl7.org/fhir/patient-definitions.html , not only the
attributes of the resources but the resources themselves also have "Control"
values, and the "Control" value for a resource itself is always '1..1'
(again, as far as I saw, and I cannot imagine how it would be anything
else).

I'm not coming up with a good way to ask this, possibly because I am so
confused as to why documention of a resource should relate the cardinality
of that resource-- it should only have a cardinality in the context of being
linked to as (part of) an attribute from another resource.

Does my confusion make sense?


Reply to this email directly or view it on GitHub
https://github.com/tnavatar/clingen-data-model/issues/113 .

**Comment by larrybabb** [comment]
One other observation about the "Control" property on the detailed descriptions of attributes, entities and relationships in the FHIR Resource pages.

The "Control" label is a hyperlink to the section [1.11 Conformance](http://hl7-fhir.github.io/conformance-rules.html#conformance) section of the spec

Which I believe may provide some potential justification for all of the various "control-like" info that is related to the Resource, attributes and relationships.  Again, it seems like it is wide open to interpretation and most certainly not clear.  However, it does provide additional insights into how FHIR perceives the boundaries of what they should and should not include in their specification.

**Comment by bpow** [comment]
I figured it was probably a build artifact, in which case it is one that we should not try to mimic. I just wanted to make sure I wasn't missing something. Would it be OK with you to get rid of the control values on the top-level resources of our documentation?

Since you are our Prometheus (bringer of FHIR) and have the contacts in the area, I think it would be worthwhile to suggest that they address this.

**Comment by larrybabb** [comment]
I will add this to the FHIR issues list.  In the meantime, I am fine with
removing the control values from the top level resources of our
documentation.

From:  Bradford Powell notifications@github.com
Reply-To:  tnavatar/clingen-data-model
<reply+000ea21b5ae186cb6448590f895fbbe79e1793dc3888c70192cf00000001116e06b59
2a169ce04941cc7@reply.github.com>
Date:  Friday, May 15, 2015 3:10 PM
To:  tnavatar/clingen-data-model clingen-data-model@noreply.github.com
Cc:  Lawrence Babb larry.babb@gmail.com
Subject:  Re: [clingen-data-model] What does it mean for a resource to have
a 'control' value (#113)

I figured it was probably a build artifact, in which case it is one that we
should not try to mimic. I just wanted to make sure I wasn't missing
something. Would it be OK with you to get rid of the control values on the
top-level resources of our documentation?

Since you are our Prometheus (bringer of FHIR) and have the contacts in the
area, I think it would be worthwhile to suggest that they address this.


Reply to this email directly or view it on GitHub
<https://github.com/tnavatar/clingen-data-model/issues/113#issuecomment-1024
96299> .

**Comment by bpow** [comment]
Thanks for sending the query along. I actually went ahead and hardcoded 'Control: 1..1' for top-level resources in the resource.erb template, but we can discuss later whether this should stay or not.

For now, I will go ahead and close this issue.
