### ISSUE TITLE
Question on Gene and Allele attributes

### ISSUE THREAD

**Issue by pmcgarvey** [tnavatar/clingen-data-model#122]
Hi

In looking at the model and Baylor's sample documents in geneboree I did not find two attributes used routinely in genomics in either Gene or Allele models. Chromosome number and Strand. 

Chromosome number is a required field in many genomic file formats like VCF,  BED files and probably more. It seems I can only obtain this via looking up a genomeic reference ID like NC_000023.11 if provided. Stand is not as critical but can help orient yourself for certain use cases. 

Do you think these items could be added? The data would be far more useful from my point of view.

Thanks 

Peter McGarvey

**Comment by srynobio** [comment]
This might be something we could add to SimpleGenomicAllele. 

Thoughts @larrybabb

**Comment by pmcgarvey** [comment]
That would be a good place for it I think. Gene was the other option but I like SimpleGenomicAllele best.

**Comment by larrybabb** [comment]
We had considered modeling "Chromosome" as a concept in one of the early phases of the conceptual model, but decided to simplify the scope and keep it as an attribute.  As such, we placed on the most specific class "ChromosomeReferenceSequence" in the conceptual model.  As you can see in the ReferenceSequence section of the conceptual model we selectively chose certain types of ReferenceSequences to support initially. Again, these choices were made to focus the scope and get an initial release of the model out.  Would it be fair to move the chromosome attribute from the ChromosomeReferenceSequence to the superclass, GenomicReferenceSequence, so that any genomic simple allele would have a reference to a genomic sequence which would contain a required chromosome value?  Or do you need to have a chromosome value associated with transcript and amino acid reference sequences as well?

**Comment by pmcgarvey** [comment]
I see I missed it in the model and the examples. My mistake I expected to find it elsewhere and did not look close enough. Yes I can work with it there I think. Thanks
