### ISSUE TITLE
GA4GH is investigating switch from AVRO to ProtocolBuf

### ISSUE THREAD

**Issue by larrybabb** [tnavatar/clingen-data-model#128]
We should keep an eye on the current issue [GA4GH/schemas #343](https://github.com/ga4gh/schemas/issues/343) related to switching from AVRO to ProtocolBuf in the GA4GH.  Since we are considering AVRO in order to be consistent with the GA4GH documentation, we should try to avoid any undo effort if they appear to be on a trajectory to move to ProtocolBuf.

**Comment by tnavatar** [comment]
I just got through reading through that thread and some of the related links. It’s not clear what they gain going to ProtoBuff, except that it’s a more mature platform based around code generators, which might make a standard implementation a bit easier (also it’s the Google standard, which probably helps integrate with the Google Genomics platform). It still seems to have many of the same problems they have with Avro though.

That said, there were some benefits in Avro they obviously wanted (and we might want too):

1) An IDL is an expressive and precise way to describe a model. We would gain a lot by using one.
  a. If we use an IDL to describe our model, we should pick one with an existing standard, rather than trying to invent our own.
2) Avro has (had?) a lot of momentum and is built into important open source projects (the Hadoop stack)

Lastly there is the benefit of using things that help us converge with the ga4gh. If they’re moving away from Avro, obviously we lose that last benefit if we go with it anyway.

It seems like the major issue they have is that they’re trying to adapt a language intended for a different purpose and add their own custom definition to what the language ‘means’: (for an example: https://docs.google.com/document/d/1Uk226saXZb5eQfSrhy6_tw1HSDB8OnzqvTcR5uXjERA/edit#), effectively creating their own IDL without really writing a specification for it. They _could_ just say their standard is Avro JSON, but Avro JSON isn’t particularly idiomatic in JSON terms, so that seems like a painful choice to make just to accommodate the limitations of the IDL. Naturally we’d have the same problem if we went with Avro (or any of the popular serialization formats, including ProtoBuff or Thrift—they don’t define a JSON interpretation, but we would have to).

FHIR seems to solve the problem by making their own IDL (in MS Excel!), setting XML and the XML schema as the primary formalism for describing resources (http://hl7-fhir.github.io/formats.html) and defining the JSON implementation in terms of the XML (http://hl7-fhir.github.io/json.html). Meanwhile an RDF/linked data description is only just beginning to be worked on: http://hl7-fhir.github.io/rdf.html)

In Ronak’s work implementing our model, he started an implementation based on the one formalism we had (the XML schema), and has been interpreting it into JSON-LD. I think this suggests how important the formalism is relative to a looser description of the model. I think we should have a formalism like this, but I don’t know that it tells us what to use, especially as JSON-LD seems to be the ‘first class’ serialization format of our model. RDF Schema, perhaps?

**Comment by bpow** [comment]
Here's my $0.02, not completely thought out yet and I reserve the right to flip-flop at a later date:

I agree that a switch from Avro to protobuf for the GA4GH solves a particular problem for them in terms of data representation (specifically it appears they are in an "uncanny valley" where the serialization is JSON but not quite the JSON that would be easiest for them to work with). From our standpoint, we have put a fair bit of effort to-date into being serialization-independent. Maybe some of this effort is misplaced, but I do think that it is worthwhile for us to continue to consider the _model_ separate from the _serialization_. In particular, there is a fair bit of behavior that we specify (to put another way, we are not just specifying grammar but also semantics). From that standpoint, a serialization framework, by itself, will not capture the documentation we are trying to produce. Something like [swagger](http://swagger.io) is great for documenting an API, but it would be difficult to describe elements of canonicalization in this framework.

It may helpful to come up with a "wish list" of features for any data formalization/description framework (whatever that should be called) in order to more systematically evaluate alternatives.

Here are some things I would like:
1. A single source for the machine-readable description and model documentation. This helps avoid bit-rot by locality of the docs with the data description itself.
2. Easy version control (the spreadsheets in FHIR are serialized to XML and put in version control, but I think this is awkward).
3. Something that is not more verbose than it needs to be, so that the important parts are not lost in boilerplate.
4. Easy incorporation into an existing reference implementation.
5. Nothing that will make things too difficult for our current collaborators or potential future users.
6. Easy enough for qualified people to contribute. This should ideally include low dollar-cost of any commercial software if used for modelling, but also low barrier to entry in terms of learning the system.

Ideally there is an IDL out there that would meet our needs, but if not, then I don't think we should shy away from the possibility of creating some structured representation of our data model. Yes, I know that is how we end up with 18 standards instead of 17, but we don't have to call it a standard, we can just call it the structured description of our model...
