### ISSUE TITLE
amino-acid alleles

### ISSUE THREAD

**Issue by ronakypatel** [tnavatar/clingen-data-model#137]
Going by the value list (http://datamodel.clinicalgenome.org/allele/implementation/value_set_list/primary_amino_acid_change_type.html), is it easy to distinguish frameshift_truncation and frameshift_elongation for an amino-acid allele? Similarly, is it easy to distinguish conservative_inframe_deletion and disruptive_inframe_deletion? 

Please let me know if you have examples of alleles like each of above category.

Instead mother terms in such cases, frameshift_variant, inframe_deletion and inframe_insertion should be easy to delineate.

**Comment by srynobio** [comment]
Sorry @ronakypatel what are you trying to distinguish?  The difference between them?

**Comment by ronakypatel** [comment]
No, given an allele presented in the form of HGVS, if it is frameshift_truncation or frameshift_elongation? say for example: LRG_311p1:p.Arg14Lysfs, it is frameshift, but if it is truncation or elongation. 

Similarly LRG_321p3:p.Arg280_Arg283delinsHis, Is it conservative_inframe_deletion, disruptive_inframe_deletion?

**Comment by srynobio** [comment]
You would need to have more information then the HGVS expression to make a proper annotations.

**Comment by ronakypatel** [comment]
Thanks for the reply.

I would ask like what information is needed?

In addition, explanation of trade-of between the amount of
information/methods that go behind discriminating framshift_truncation and
frameshift_elongation and knowledge that will be gained by discriminating
it? e.g. frameshift_truncations are more deleterious compared to the
elongations, something like that.

**Comment by cbizon** [comment]
?I think that we should replace frameshift_truncation and frameshift_elongation with the parent node (frameshift_variant?).  The truncation/elongation can go into the secondary annotations if people are excited about it.

I think(?) that the others can be derived from the HGVS expression...

Chris

**Comment by ronakypatel** [comment]
@cbizon , I strongly feel so.

I am trying to pull out some example to distinguish disruptive and conservation deletion. I think I have trouble understanding conservative and disruptive deletion/insertions.

This is what definition says:

disruptive_inframe_deletion: An inframe decrease in cds length that deletes bases from the coding sequence starting within an existing codon.

conservative_inframe_deletion: An inframe decrease in cds length that deletes one or more entire codons from the coding sequence but does not change any remaining codons.

shouldn't the disruptive_inframe_deletion be frameshift?

How about these:

NP_000539.2:p.Gly630_Leu631delinsAspAla : This is neither conservative nor disruptive.

NP_066268.1:p.Thr191_Phe197del: What kind of deletion it is conservative/disruptive?

**Comment by cbizon** [comment]
A frameshift results when there is an underlying insert/deletion of 1 or 2 bases in the transcript.

If there is an insert/deletion of 3,6,9 etc bases, then the amino acid change is not a frameshift.

Let's consider a deletion.  If amino acids are removed from the sequence, but otherwise all AA are left unchanged, then that is a conservative deletion.  So NP_066268.1:p.Thr191_Phe197del would be a conservative deletion.

If the overall length of the protein changes (so it's a deletion) but not all of the aa change from that point on (so it is not a frameshift) and it is not conservative, then it is disruptive.  In other words, it would show up as a delins where the number of things inserted is less than the number deleted.  This would happen, for instance, if the last base of one codon and the first two of the next were deleted.   The two original AA would be deleted and replaced with a single (probably different) amino acid.

The Gly630_Leu631delinsAspAla? is not a deletion, because the length doesn't change.  It is a missense.

And the same is all true in reverse for an insertion.

**Comment by ronakypatel** [comment]
NP_000072.2:p.Leu2354_Asp2356delinsMetfs would be disruptive_deletion,
although it says fs in hgvs?

http://www.ncbi.nlm.nih.gov/clinvar/variation/65546/

**Comment by ronakypatel** [comment]
I think it is frameshift after Met.

**Comment by ronakypatel** [comment]
Stop_gained or frameshift?
NP_000305.3:p.Thr319Terfs (http://www.ncbi.nlm.nih.gov/clinvar/variation/71118/)

start_lost or frameshift?
NP_000050.2:p.Met1Ilefs: (http://www.ncbi.nlm.nih.gov/clinvar/variation/37872/)

**Comment by cbizon** [comment]
I think that most of these are cleared up, so I will close this issue and start a new issue dealing with the ones that are not disjoint, such as the two in the last comment.
