### ISSUE TITLE
Terms for Condition Mechanism

### ISSUE THREAD

**Issue by cbizon** [tnavatar/clingen-data-model#160]
ACMG uses as evidence of pathogenicity the fact that a particular variant is nonsense coupled with the fact that LOF variants are known mechanisms of disease.  We need a set of terms to use for mechanisms of disease.

The UNC parsing has a single attribute with terms
Loss of Function (truncating or missense variants)
Gain of Function (missense variants or inframe indels)
Unknown or Multiple

These aren't bad, but we need to decide whether Loss of Function is a term that we want to apply to missense.  While correct in one sense, I'm not sure that's how the term is colloquially used.  Also, is there a reason that inframe indels are only listed under gain of function?

**Comment by bpow** [comment]
What we are trying to get to here is an assertion beyond the direct "molecular effect" (e.g. Lys234Pro) to what effect that actually has on the function of the protein-- for instance loss of function by disrupting the structure of a binding site, or gain of function by leading to constitutive activation for examples.

In general it is difficult to automate this process, but truncating mutations are often assumed to be LoF (although a truncating mutation in the last 1.5 exons may escape nonsense mediated decay, and if if the c-terminus contains a domain involved in regulation, then it could result in GoF. There are always exceptions...)

The value here will often be "Unknown" unless there is experimental evidence to support LoF or GoF, or someone invokes the fact that truncating variants are typically LoF.

Inframe indels could be LoF or GoF, so if we are making exhaustive lists they should be included as possibilities in both.

**Comment by cbizon** [comment]
Right, I guess my reading of that ACMG guideline is that the invocation of truncating->LOF is how it will actually be applied. Somebody will say "hmm, I have a nonsense variant, and there are 20 pathogenic variants that are nonsense" or "There are 20 pathogenic variants and none of them are nonsense".  In the first case, one would say that LOF is a likely mechanism of action and in the latter, you would probably say unknown. 

My slight concern about the term LOF is that it really means that the product loses function, but we often talk about LOF variants as a definition including only nonsense, frameshifting indels and sometimes splice variants, and I'm concerned that there could be confusion between these two terms.

Finally, is there often functional or other evidence that LoF or GoF is actually the mechanism of a particular disease?  (something other than the variant based inferences above?)

**Comment by rrfreimuth** [comment]
LoF and GoF may be fairly clear in some cases, but not always.  In PGx, the impact a variant has on the function of a given enzyme may be drug-dependent (e.g., more severe for one drug than another).  Therefore, I've always been a little uncomfortable using a blanket statement of pathogenicity without including a reference point (e.g., pathogenicity for which function or disease).  Another example could be a variant that alters the level of expression of an enzyme but not its catalytic activity.  It seems odd to say the variant causes LoF when the function itself it unaffected; a more accurate statement would reference the level of expression rather than activity.

More nuances... just what we need, right?
