### ISSUE TITLE
Revisit coding of start/end

### ISSUE THREAD

**Issue by cbizon** [tnavatar/clingen-data-model#22]
We have decided to use the "alignment method", but I would like to have  further discussion about this.  

The alignment method works well in a VCF where the point is to keep information about variants.  However, we have separated out variant from coordinate, and now we are using alignment to talk about a coordinate.

This is a problem because the coordinate now includes bases that we're not actually interested in.  Two illustrations:

1) Suppose we have a T in the reference, and in the population there are three alleles: T/A/-.  The deletion of the T must now occur at a different ReferenceCoordinate.

2) We attach a region type to ReferenceCoordinate independent of any alleles at that location.  Suppose that we have a deletion of the first two bases of an intron.   We would like this to have a regionType of "splice site", but our reference coordinate will have to include both the intronic bases, plus one exonic base, meaning that the region type will be something else.

Note that neither problem is unfixable or unhandleable in the alignment format, but they point, in my mind to a somewhat un-natural way of describing these coordinates: one that sort of requires you to know what the allele is going to be before you define the place where it occurs.

**Comment by larrybabb** [comment]
Great points. Look forward to working through this.

We may also want to discuss the notion of provenance or source to include in
the allele model.  I think Aleks team will need a little guidance on
how/where to provide the information tracking from where the SimpleAllele
originally (and subsequently) came as well as the activity (clinical
testing, lit curation, etc.).  I know it's a slight extension, but this is
an Allele Registry, which means there needs to be some notion of a
Registrant.

From:  cbizon notifications@github.com
Reply-To:  tnavatar/clingen-data-model
<reply+000ea21b19cd9c8f96b161e9ced97a3850cdd6e28aad41ec92cf0000000110fb228b9
2a169ce03741504@reply.github.com>
Date:  Tuesday, February 17, 2015 10:38 AM
To:  tnavatar/clingen-data-model clingen-data-model@noreply.github.com
Subject:  [clingen-data-model] Revisit coding of start/end (#22)

We have decided to use the "alignment method", but I would like to have
further discussion about this.

The alignment method works well in a VCF where the point is to keep
information about variants.  However, we have separated out variant from
coordinate, and now we are using alignment to talk about a coordinate.

This is a problem because the coordinate now includes bases that we're not
actually interested in.  Two illustrations:

1) Suppose we have a T in the reference, and in the population there are
three alleles: T/A/-.  The deletion of the T must now occur at a different
ReferenceCoordinate.

2) We attach a region type to ReferenceCoordinate independent of any alleles
at that location.  Suppose that we have a deletion of the first two bases of
an intron.   We would like this to have a regionType of "splice site", but
our reference coordinate will have to include both the intronic bases, plus
one exonic base, meaning that the region type will be something else.

Note that neither problem is unfixable or unhandleable in the alignment
format, but they point, in my mind to a somewhat un-natural way of
describing these coordinates: one that sort of requires you to know what the
allele is going to be before you define the place where it occurs.

‹
Reply to this email directly or view it on GitHub
https://github.com/tnavatar/clingen-data-model/issues/22 .

**Comment by larrybabb** [comment]
I cleaned this up, and added some data, so it's easier to review and discuss.
--Shawn

## VCF-Style (non-population)

| Chr | POS | REF | ALT | Type |
| --- | --- | --- | --- | --- |
| 1 | 131423 | G | A,T | SNP, SNP |
| 1 | 1528654 | CAA | CA,C | Deletion, Deletion |
| 1 | 894890 | A | AAGAC | Insertion |

## HGVS-Style

| Ref | Coord | Start | End | Ref | Alt | Type |
| --- | --- | --- | --- | --- | --- | --- |
| CV1 | g.100G>T | 100 | 100 | G | T | Substitution |
| CV2 | g.101_102delTT | 101 | 102 | TT | - | Deletion |
| CV3 | g.101_02insA | 101 | 102 | - | A | Indel |

## Bizon-Style (incl/excl)

| Ref | Coord | Start | End | Ref | Alt | Comments |
| --- | --- | --- | --- | --- | --- | --- |
| CV1 | g.100G>T | 100 | 101 | G | T |  |
| CV2 | g.101_102delTT | 101 | 103 | TT | - |  |
| CV3 | g.101_102insA | 102 | 102 | - | A | dupes are inserts |
| CV4 | g.101_103delTTAinsGT | 101 | 104 | TTA | GT |  |

**Comment by sharrison6** [comment]
The rs# entry in dbSNP includes a "Variant Class": SNV (single nucleotide variation) or DIV (deletion/insertion variation). 
From what I've seen a deletion and substitution at the same position would not have the same rs# because they have different variant classes.
For example:
http://www.ncbi.nlm.nih.gov/projects/SNP/snp_ref.cgi?rs=397515951
http://www.ncbi.nlm.nih.gov/projects/SNP/snp_ref.cgi?rs=397515952
and
http://www.ncbi.nlm.nih.gov/projects/SNP/snp_ref.cgi?rs=397515931
http://www.ncbi.nlm.nih.gov/projects/SNP/snp_ref.cgi?rs=193922378

I've yet to see an rs that has "SNV/DIV"...so I'll keep looking

**Comment by larrybabb** [comment]
I think this means that we cannot associate dbsnp rs ids on the
ReferenceCoordinate component.  Although we do support putting multiple rs
ids on the coordinate, so it may work. It is just not as useful since we can
no longer assume that a ReferenceCoordinate is essentially the same as a
dbsnp rs id concept.

From:  sharrison6 notifications@github.com
Reply-To:  tnavatar/clingen-data-model
<reply+000ea21ba10068e9cbc74d7d9503c0f4f7c6b37f52574aa692cf0000000110fb719a9
2a169ce03741504@reply.github.com>
Date:  Tuesday, February 17, 2015 4:16 PM
To:  tnavatar/clingen-data-model clingen-data-model@noreply.github.com
Cc:  Lawrence Babb larry.babb@gmail.com
Subject:  Re: [clingen-data-model] Revisit coding of start/end (#22)

The rs# entry in dbSNP includes a "Variant Class": SNV (single nucleotide
variation) or DIV (deletion/insertion variation).
From what I've seen a deletion and substitution at the same position would
not have the same rs# because they have different variant classes.
For example:
http://www.ncbi.nlm.nih.gov/projects/SNP/snp_ref.cgi?rs=397515951
http://www.ncbi.nlm.nih.gov/projects/SNP/snp_ref.cgi?rs=397515952
and
http://www.ncbi.nlm.nih.gov/projects/SNP/snp_ref.cgi?rs=397515931
http://www.ncbi.nlm.nih.gov/projects/SNP/snp_ref.cgi?rs=193922378

I've yet to see an rs that has "SNV/DIV"...so I'll keep looking

‹
Reply to this email directly or view it on GitHub
<https://github.com/tnavatar/clingen-data-model/issues/22#issuecomment-74755
266> .

**Comment by srynobio** [comment]
After Reviewing the Bizon-Method I realized it quite similar to a format we developed called [GVF](http://www.sequenceontology.org/resources/gvf.html).  It's based on the GFF3 format.  We currently maintain the format, and all the tools (including GVF to VCF converters, etc) related.  

| Chr | Ref | Start | End | Ref | Alt | Type |
| --- | --- | --- | --- | --- | --- | --- |
| chr22 | 43088928 | 43088928 | Reference_seq=- | Variant_seq=C | insertion |  |
| chr12 | 53701673 | 53701677 | Reference_seq=GCTCA | Variant_seq=- | deletion |  |
| chr9 | 107560784 | 107560784 | Reference_seq=G | Variant_seq=A | SNV |  |

Just thought I would mention it as apart of the discussion.  If we can see unity between the two methods it might give us a leg up in selling it to the larger community. 

Thoughts?

**Comment by larrybabb** [comment]
I definitely hear you on the "selling it to the larger community", we
definitely should leverage that aspect.  However, we must be clear to point
out the exclusive part of the inclusive-exclusive approach that Chris has
established.  I believe the delta between the Bizon-method and GVF is that
the end position of the bizon method will always be 1 greater than the GVF
except for insertions.

Chris ­ please verify the above and let us know whether we should consider
just switching to the GVF approach.  I will try to look at the GVF spec
later to see if I can appreciate why GVF does not take a "consistent" and
"logical" approach to the numbering like you are suggesting in your
inclusive-exclusive model.  We will have to have a good argument when others
challenge it as well as clear statements as to the differences.

Larry

From:  Shawn Rynearson notifications@github.com
Reply-To:  tnavatar/clingen-data-model
<reply+000ea21be4b32299997f32a10fe3a78e64498c0c6ec0e6f292cf0000000110fb81179
2a169ce03741504@reply.github.com>
Date:  Tuesday, February 17, 2015 5:22 PM
To:  tnavatar/clingen-data-model clingen-data-model@noreply.github.com
Cc:  Lawrence Babb larry.babb@gmail.com
Subject:  Re: [clingen-data-model] Revisit coding of start/end (#22)

After Reviewing the Bizon-Method I realized it quite similar to a format we
developed called GVF http://www.sequenceontology.org/resources/gvf.html .
It's based on the GFF3 format.  We currently maintain the format, and all
the tools (including GVF to VCF converters, etc) related.

ChrRefStartEndRefAltType
chr224308892843088928Reference_seq=-Variant_seq=Cinsertion
chr125370167353701677Reference_seq=GCTCAVariant_seq=-deletion
chr9107560784107560784Reference_seq=GVariant_seq=ASNV

Just thought I would mention it as apart of the discussion.  If we can see
unity between the two methods it might give us a leg up in selling it to the
larger community. 

Thoughts?

‹
Reply to this email directly or view it on GitHub
<https://github.com/tnavatar/clingen-data-model/issues/22#issuecomment-74767
803> .

**Comment by cbizon** [comment]
It's interesting - this seems to be a (relatively) recent change.  So back in build 137 (which I have a copy of lying around), rs26 had alleles T/G/-.

But by the current build (143), the deletion has been pulled out into its own id, ?rs375794636.  I'm not enough of a dbsnp guru to be able to figure out when that happened exactly, but I'm guessing that there was a build where they systematically pulled these apart.

Chris

**Comment by cbizon** [comment]
RE: GVF format

I think (?) that the GVF format is identical to what we were calling the "Variant Format" in our earlier discussion.   The drawback of this method compared to the interval method (or inclusive-exclusive) is that the ref and end are not interchangeable.  You really need both to distinguish between talking about a single-base locus and talking about the insertion point just before the base.

**Comment by sharrison6** [comment]
You're right, Chris. rs375794636 was created in build 138. So prior to 138, rs26 and rs375794636 would have been together (I think). However, for the 2 examples I used above, all 4 rs#s were created in 136. So prior to 138 not all rs#s were grouped by position (regardless of type)

**Comment by srynobio** [comment]
Just a thought on the first comment:

_2) We attach a region type to ReferenceCoordinate independent of any alleles at that location. Suppose that we have a deletion of the first two bases of an intron. We would like this to have a regionType of "splice site", but our reference coordinate will have to include both the intronic bases, plus one exonic base, meaning that the region type will be something else._

I think this would be cleared up based on the exclusive list discussion we had yesterday.  Now having the cardinality of 0..\* would allow this annotation:
- intron(SO:0000188), exon(SO:0000147)

Or perhaps a single annotation of:
- cis_splice_site([SO:0001419](http://www.sequenceontology.org/browser/current_svn/term/SO:0001419))

**Comment by cbizon** [comment]
I don't really see how the annotation helps.  IMO it makes things more confusing.  So lets say I have a sequence like ACTGACTctacga, where capital = exon and lowercase = intron.

Lets say that there is a deletion of the ct.  That deletion occurs in the intronic splice site.  But if we have to define the region as Tct, then that region is not fully in the intronic splice site.  Now, one would have to say that it is a region that is in both the splice site and the exon, or in some complex region or something.  And now when we say that the allele happens at this location, there are region annotations that are misleading if we use them to interpret the allele, since the allele does not do anything to any exonic bases.

**Comment by srynobio** [comment]
I literally understand what you mean when you say _[an] allele does not do anything to any exonic bases_, but the transcript annotations are used to denote the features "splice_site" which is the information of importance.  Although the exonic base is not the allele this exon will be effected. 
[cis_splice_site](http://www.sequenceontology.org/browser/current_svn/term/SO:0001419)
[extended_cis_splice_site](http://www.sequenceontology.org/browser/current_svn/term/SO:0001993)

**Comment by cbizon** [comment]
cis_splice_site is (I think) the annotation that most clearly expresses what the variant affects.  But the coordinate defined using the alignment has to use extended_cis_splice_site since it also includes that exonic base.  That leads to a mismatch (IMO) between what we want to say about the allele and what we are forced to say about the coordinate because of the inclusion of an extraneous base.

**Comment by cbizon** [comment]
Oh actually, sorry, I don't think that extended_cis_splice is right either, because that is intronic bases only.    This is for the single region idea.  If you had the multiple regions then a combo of exon and cis_splice_site would be correct for the region, but would still be misleading when applied to the allele (because of the exon).

**Comment by cbizon** [comment]
We agreed to a 1-based interval schema and implemented that.   Closing the issue, though we are currently discussing a move to the more common 0-based interval schema in another thread.
