### ISSUE TITLE
SO term for ReferenceSequence

### ISSUE THREAD

**Issue by tnavatar** [tnavatar/clingen-data-model#23]
Tiny issue, but I'm drafting resource documentation and I was looking for an SO term for ReferenceSequence. The nearest I could find is consensus_region (SO:0000994).

Does this seem like a good enough fit?

**Comment by srynobio** [comment]
Because we are abstracting sequence, transcript and gene into one concept it gets difficult because SO divides the idea of a reference into [sequence](http://www.sequenceontology.org/browser/current_svn/term/SO:0001505), [transcript](http://www.sequenceontology.org/browser/current_svn/term/SO:0000673) and [gene](http://www.sequenceontology.org/browser/current_svn/term/SO:0000704).  The nearest term in abstract which would include all of these ideas would be [biological_region](http://www.sequenceontology.org/browser/current_svn/term/SO:0001411).

**Comment by tnavatar** [comment]
Let's go with that for now then, addressed in 667594a
