### ISSUE TITLE
Adding ValueSet section to the main page.

### ISSUE THREAD

**Issue by srynobio** [tnavatar/clingen-data-model#36]
I've created a directory on the repo for all the ValueSets created.  Do you think we should have a separate section for them instead of lumping them with the conceptual model?

**Comment by larrybabb** [comment]
This sounds like a reasonable idea. These ValueSets are really shared
between conceptual and resource models, so they sit at the same or higher
level, similar to something like datatypes.

From:  Shawn Rynearson notifications@github.com
Reply-To:  tnavatar/clingen-data-model
<reply+000ea21bfba6b5dff13b1321d1139e1b2771131282e4216592cf000000011105ebd19
2a169ce0383aa4a@reply.github.com>
Date:  Wednesday, February 25, 2015 3:00 PM
To:  tnavatar/clingen-data-model clingen-data-model@noreply.github.com
Subject:  [clingen-data-model] Adding ValueSet section to the main page.
(#36)

I've created a directory on the repo for all the ValueSets created.  Do you
think we should have a separate section for them instead of lumping them
with the conceptual model?

‹
Reply to this email directly or view it on GitHub
https://github.com/tnavatar/clingen-data-model/issues/36 .

**Comment by tnavatar** [comment]
That seems like a good idea to me as well. I'll create this.

**Comment by tnavatar** [comment]
Resolved by 446c8f8
