### ISSUE TITLE
FHIR JSON-LD interoperability

### ISSUE THREAD

**Issue by tnavatar** [tnavatar/clingen-data-model#37]
A question, mostly for Larry:

Are you, or is anyone, aware of the efforts on the FHIR team to incorporate Sematic Web standards? http://wiki.hl7.org/index.php?title=RDF_for_Semantic_Interoperability

It's a little tricky because it looks like they're puzzling this out right now and are not close to having published standards. I'm wondering if there's any context to this effort that could be relevant to ours.

**Comment by larrybabb** [comment]
This is the first I have heard of it.  I do not have any additional info to
add.

You know what would be super helpful.  If someone could show me a system
that is available today that is based on RDF that is super useful to a given
community in a way that translates to curation or allele registration or any
kind of production quality system.  I just can't seem to put my finger on
one.  I get that they are great for searching around and finding
relationships, but not sure how that solves the data integrity and quality
concerns that most targeted applications require. It seems like the ontology
makers can create ontologies that don't necessarily translate to everyone's
needs.  (as usual, I digress)

From:  tnavatar notifications@github.com
Reply-To:  tnavatar/clingen-data-model
<reply+000ea21b7d0cea45f452f2700af90492cb346abbe2b3bcfb92cf00000001110c6ecd9
2a169ce038c423e@reply.github.com>
Date:  Monday, March 2, 2015 1:32 PM
To:  tnavatar/clingen-data-model clingen-data-model@noreply.github.com
Subject:  [clingen-data-model] FHIR JSON-LD interoperability (#37)

A question, mostly for Larry:

Are you, or is anyone, aware of the efforts on the FHIR team to incorporate
Sematic Web standards?
http://wiki.hl7.org/index.php?title=RDF_for_Semantic_Interoperability

It's a little tricky because it looks like they're puzzling this out right
now and are not close to having published standards. I'm wondering if
there's any context to this effort that could be relevant to ours.

‹
Reply to this email directly or view it on GitHub
https://github.com/tnavatar/clingen-data-model/issues/37 .

**Comment by tnavatar** [comment]
I've been searching for this; I have the same question. Doing a quick lit review turns up some stuff, mostly in 2008-2009, but not as much after. There are a good number of people doing research in the field, but not as many people announcing working applications.

There are some important resources that have SPARQL endpoints returning data as RDF, for example UniProt (http://beta.sparql.uniprot.org). It's hard to know how well utilized these are, but it means someone found it interesting to expose their data this way. i2b2 also has a SPARQL endpoint developed within the consortium. That said, these seem to be more the exception than the rule, and linked data only gets significant utility when a significant number of databases in your problem domain are exposed this way.

The concept of linked data itself seems to have a lot of potential. One of the major issues in our domain is that relevant data are spread out across many different databases (to which we will be adding at least one more). Linked data addresses this problem; bioinformatics is frequently cited as a domain that has great potential to benefit from linked data. Once linked data is built around an ontology (OWL is designed for this), reasoners can be built to make even more complicated queries around linked data. Machine learning and AI people have a natural interest in it for that reason (i.e. Carlos).

I'm trying to answer the question of why this hasn't caught on (and whether it's likely to in the future). Some of the important standards are relatively recent, and it takes a critical mass of people providing SPARQL endpoints before its utility shows up. Without this it's a just a more sophisticated (and complicated) approach to RESTful querying (which might actually be enough to justify it in some cases).

I think it might be worth it to ask the other people on the grant what their interest in linked data is, whether it's just an attempt to expand the set of linked data resources available out there, or if they actually have specific use cases for it. Perhaps we could ask for a presentation on one of the Monday informatics calls. 

The frustrating thing is that this feels a bit like a distraction from our current goals. My sense is that we have to follow the FHIR example: produce our model, and make the linked data representation of that a different task (just not one that we lose track of if its deemed to be of importance).

**Comment by cbizon** [comment]
Make a discussion page linked from the top.

**Comment by cbizon** [comment]
Larry - I've created source/allele/fhir.md which is linked to from the discussion section of allele/index.md.  I'm not totally sure whether I've fulfilled this point or not, so I'm leaving the ticket open until you get a chance to look it over.

**Comment by cbizon** [comment]
I recall Larry saying that he wanted to update this page (which I am all for), so I'm assigning ownership to him.
