### ISSUE TITLE
Figure out how to make Larry a contributing member.

### ISSUE THREAD

**Issue by larrybabb** [tnavatar/clingen-data-model#54]
Wondering why my contributions are not showing up in the monitoring of the project. Any thoughts?

**Comment by tnavatar** [comment]
I think I understand why this is happening (because I have the same problem). Your local Git client pushes with the email lbabb@geneinsight.com, but I wonder if your GitHub account wasn't set up with a different e-mail. If you associate your geneinsight.com address with GitHub that might fix the problem.

**Comment by tnavatar** [comment]
Yeah, I just fixed this for myself and went from one commit to 50...
