### ISSUE TITLE
Question about JSON-LD

### ISSUE THREAD

**Issue by srynobio** [tnavatar/clingen-data-model#56]
First off please excuse my unfamiliarity with JSON-LD,  I'm still getting ahold of it.

My first question comes from Chris's example:

``` json
{
    "@context":"http://clingen.org/models/Gene.jsonld"
    "@id":"http://clingendb.clingen.org/Gene/G101",
    "@type":"Gene",
    "symbol": "ILK",
    "name": "integrin-linked kinase",
    "identifier":
    [
        {
            "@type":"Identifier"
            "use":"official",
            "label":"ILK",
            "system":"http://www.genenames.org/",
            "value": "HGNC:6040"
        },
        {
            "@type":"Identifier"
            "system":"http://www.ncbi.nlm.nih.gov/gene",
            "value": "3661"
        }
    ],
    "xref":
    [ 
        "http://www.genenames.org/cgi-bin/gene_symbol_report?hgnc_id=HGNC:6040",
        "http://www.ncbi.nlm.nih.gov/gene/3611" 
    ]
}
```

Is this section valid given JSON-LD [type](http://www.w3.org/TR/json-ld/#typed-values) definition i.e where are these keys being defined?

``` json
            "@type":"Identifier"
            "use":"official",
            "label":"ILK",
            "system":"http://www.genenames.org/",
            "value": "HGNC:6040"
```

Also, so far I've made one attempt at this (I hope to have more before tomorrow), what do you guys think?

``` json
{
    "@context": {
        "@vocab": "http://clingen.org/model/"
    },
    "id": "G102",
    "identifier": [
        {
            "@context": "http://www.genenames.org/about/guidelines",
            "genename": "BRCA1",
            "genesymbols": {
                "@id": "http://www.genenames.org/cgi-bin/gene_symbol_report?hgnc_id=HGNC:1100",
                "@type": "@id"
            }
        }
    ],
    "symbol": "BRCA1",
    "name": "breast cancer 1, early onset",
    "aliasSymbol": [
        "IRIS",
        "PSCP",
        "BRCAI",
        "BRCC1",
        "FANCS",
        "PNCA4",
        "RNF53",
        "BROVCA1",
        "PPP1R53"
    ]
}
```

**Comment by cbizon** [comment]
> i.e. where are these keys being defined?

Those are defined in the context.  So there's at the top that looks like:

```
"@context":"http://clingen.org/models/Gene.jsonld"
```

If you look in the Gene.jsonld file in the repo you'll see the defs for use etc...

For G102, there are a few things - I think that the context here should be the same as for G101 - that is, we have one context for all Genes.   I keep going back and forth on having one for the entire allele model.

the id tag needs to change to JSON-LD "@id" and the value should be an IRI.

For the identifier, there are a couple of things - first, I've tried to stay close to the FHIR identifiers so that translation will be easy (that's why I stayed with use, label, etc, though genename etc are perhaps more meaningful). 

Second, it is entirely allowed to have multiple contexts in a document, but from my reading it seems to me that we should try to avoid it - it makes the document harder to parse (and read).   I think we should be able to do so easily.

The genesymbols: I see what you're going for here, which is kind of an xref, but I think that you've kind of munged value types and node types together.  You could either do this:

```
"genesymbols": {
   "@value":"http://...."
   "@type":"@id"
}
```

or 

```
"genesymbols": { "@id": "http://www.ge..." }
```

But the approach that I was taking was to move the type information into the context, so in the context file I would put:

```
"genesymbols": {
   "@id":"http://clingen.org/model/allele/genesymbols",
   "@type":"@id"
}
```

Then the data would just look like:

```
"genesymbols": "http://www.genenames.org/...."
```

But systems would know that the value there was an ID. 

There is a G102 posted in the repo, as well as a couple of RS examples.

**Comment by srynobio** [comment]
Reading through your Gene.jsonld document I have a better understanding of what you're doing.  Often my first attempt and is to try and model in a more simplistic fashion, but I see the power you gain.  I'll move my focus on making more definition documents.
