### ISSUE TITLE
Documentation system for data model

### ISSUE THREAD

**Issue by tnavatar** [tnavatar/clingen-data-model#62]
I know there are some shortcomings with the current system of producing the documentation for the data model (on which we've had a few discussions). Among them:
- The model itself is represented in two different places: Visual Paradigm and a Middleman-based site (represented here). They have to be maintained separately and get out of sync easily.
- The Middleman site currently lacks some awareness of the model: it's necessary to generate links manually, UML diagrams are created with Visual Paradigm and exported to the site, and so on.
- The build process currently depends on one custodian (me) manually building and uploading the site.
- Others? (please post, these are the what I thought of off the bat)

I had started building an extension to Middleman (https://github.com/tnavatar/middleman-data-model) to address these concerns in the following ways:
- Extend Middleman so that the model can be represented entirely within the Middleman site and Visual Paradigm is no longer required.
- Add model awareness to the Middleman site: allow model attributes to be defined in the front matter of a model page and permit automatic link generation when a model object or attribute is referenced from another area of the site. Generate UML automatically, including appropriate links. I've identified PlantUML (http://plantuml.sourceforge.net) as a tool that can be incorporated in the site to do this and have started working with it to generate UML diagrams
- We need a CI process to build and publish the site, either triggered by a hook on a push to the master branch of this site or a nightly build. Shouldn't be too hard to figure out, I just need to, you know, actually do the work...

That said, sticking with Middleman isn't the only way we've discussed continuing the documentation. Other discussed alternatives:
- Piggybacking off the FHIR build process.
- Keeping everything possible in Visual Paradigm, and find/develop/adapt a tool to publish the output to the web.

There are some plusses and minuses of each approach:
### Middleman
- pros:
  - Documentation gets stored in GitHub under version control, making it easy for people to contribute to the model.
  - Based on a robust, extensible and widely used platform for building static pages.
  - Structure of the model documentation is comprehensible and relatively easy for newcomers to approach
  - Markdown-based documentation is easy to edit, even for non-technical people.
- cons:
  - Need to build out Middleman to accommodate the structure of a data model
  - Manual layout of model objects in UML probably not possible, have to be comfortable with automated layout.
### FHIR process
- pros:
  - We've been modeling our documentation off theirs, by definition it already does much of what we want our documentation to do.
  - Documentation can also be stored in GitHub
- cons:
  - Their build process is tightly wrapped around their documentation, repository, and use cases.
  - The FHIR team itself describes their process as 'not particularly robust' and specific to FHIR. (http://wiki.hl7.org/index.php?title=FHIR_Build_Process)
  - Untangling their code and adapting it to our processes may well be as much or more work than building our own around Middleman, and leave us with something less maintainable, comprehensible, and extensible.
  - The documentation source is harder to figure out than our current Middleman source, making it more difficult for external contributors to suggest alterations to the model and for current contributors to work with.
  - Important aspects of the model are maintained in a form (Excel) that integrates poorly with version control.
### VP-based process
- pros: 
  - Starts with a tool we're already familiar with.
  - Seems to have the capability of generating documentation (http://www.visual-paradigm.com/features/document-production/), though I haven't experimented much with this. This seems to be more fleshed out in the new version of VP, which we aren't using yet.
  - Only method that allows custom layout of UML diagrams, which is useful when working with complicated diagrams (i.e., the conceptual model). Robustness of automated methods for creating large diagrams is unproven.
- cons:
  - Requirement of Visual Paradigm and access to VPository probably is impenetrable barrier for non-insiders. Closes development of the model significantly.
  - Probably less customizable than either of the above solutions.
  - Will probably need external solution anyway to develop aspects of the model, like examples. May still have difficulty synchronizing between the two, particularly in maintaining links and a coherent style.

Admittedly I picked up Middleman initially because it seemed like a quick way to get documentation online when we were just getting started. As we've continued, it seems like it's extensible enough such that we can build it into a tool that serves all our needs, rather than simply being a 'just for now' solution. For this reason I've been working on the Middleman solution. That said, if it's the consensus of the group that some other approach (one of the ones listed above, or others) better meets our needs, it would probably be better that I don't spend too much more time building a documentation tool based on Middleman. We need a method to share our work that we're happy with, but the main point is to build and publish the model, and not to build stuff beyond what's necessary.

**Comment by bpow** [comment]
Another option for generating the UML diagrams is [umple](http://cruise.eecs.uottawa.ca/umple). I'm not sure that there is any particular reason to pick this over PlantUML. Umlple does not have the graphviz dependency, but PlantUML is more established (and has some tooling support, for instance an intellij plugin). Neither of them would have manual layout of UML, which may be a bit of an issue given that there is some parallel structure (e.g. subclasses of ReferenceSequence and ReferenceCoordinate) that an automated layout may not display in a manner that is most clear.

I have plantuml files for much of the conceptual model, which I'm going to go ahead and toss into the repo (they can be deleted later if we take another route).

The other thing think about how we would automate would be the generation of sub-figures as is currently being done for the sub-parts of the conceptual model. This could be do-able by having some script to extract relevant portions from the source plantuml file.

I think one goal (maybe not realistic) would be for there to be a single textual description of the data model that would be used to generate xsd and JSON-schema files and could also be processed to generate UML-like diagrams. I would envision something like a structured definition of the model (in json or xml) that we could even potentially combined with a file giving some layout hints (put ReferenceSequence at 25,0; put NucleotideReferenceSequence at 25, 30; etc.) That would be a fair amount of customization, though. I realize that we need to focus on generating a data model and documentation, not generating tools for documenting data models...

**Comment by tnavatar** [comment]
Thanks for the link, I do like your goal of generating as much as possible from a single textual description of the model. It seems realistic to me to build the UML, and potentially schema documents from that, but we'll see how far we can get.

**Comment by cbizon** [comment]
Lots to chew on here. Some (disjointed) thoughts:

FWIW, I think that the same file should generate the UML diagram as well as the textual docs.  I think that the descriptive documentation should be part of the UML files (whatever format they are in).  Preferably, references in the documentation would be based on something other than names, so that if a name changes, the documentation would not need to be changed for every place that the entity is talked about.

Based on my (limited) experience with the JSON-LD stuff recently, I think that autogenerating XSD/JSON-schema stuff may be very difficult.

One possible labor savor though, would be to build most of the examples off of a templating system of some sort.

My poking around seems to suggest that one can give dot style hints to influence the layouts in plantuml, but its never going to be "put it where you want it" style.  That said, plantuml has a lot of nice plugins etc.

**Comment by bpow** [comment]
I've done a bit more thinking about a potential "canonical format" for the model. Partially influenced by looking at the ga4gh schemas, I was prompted to look again at [avro](http://avro.apache.org).

Avro allows models to be expressed in an IDL format or in JSON. Just to throw this out there, for the SimpleAllele portion of the reference model, we would have something like this:

```
@namespace("org.clingen.allele")
protocol SimpleAllele {

    enum IdentifierUse {
        usual,
        official,
        temporary,
        secondary
    }

    record Identifier {
        union {IdentifierUse, null} use;
        union {string, null} label;
        union {string, null} system;
        union {string, null} value;
    }

    enum SequenceClass {
        NUCLEOTIDE_GENOMIC,
        NUCLEOTIDE_ALLELE,
        AMINO_ACID
    }

    record ReferenceCoordinate {
        /**
        The set of identifiers that describe the ReferenceCoordinate
        */
        array<Identifier> identifier = [];
        /**
        Start position (0-based, inclusive; "between bases")
        */
        int start;
        /**
        End position (0-based, exclusive; "between bases")
        */
        int end;
        /**
        The reference allele at this position (here for convenience)
        */
        string refAllele;
        /**
        The concrete subtype of ReferenceCoordinate according to the
        conceptual model (for type-safety when referring to
        SimpleAlleles and ReferenceSequences
        */
        SequenceClass sequenceClass;
    }

    record SimpleAllele {
        /**
        The set of identifiers that describe the SimpleAllele
        */
        array<Identifier> identifier = [];
        /**
        HGVS expression representing the simple allele
        */
        string allele;
        /**
        The IRI of the CanonicalAllele associated with this SimpleAllele.

        (cannot use the CanonicalAllele itself until avro supports
        circular references)
        */
        string canonicalAlleleIRI;
        /**
        The concrete subtype of SimpleAllele according to the
        conceptual model (for type-safety when referring to
        ReferenceCoordinates and CanonicalAlleles
        */
        SequenceClass sequenceClass;
        /**
        The location of this allele relative to its corresponding
        reference sequence
        */
        ReferenceCoordinate referenceCoordinate;
    }

}
```

The JSON format produced from this is a bit more verbose, so I'm not including all of it here, but here's a portion:

``` json
{
   "name" : "SimpleAllele",
   "fields" : [
      {
         "doc" : "The set of identifiers that describe the SimpleAllele",
         "name" : "identifier",
         "default" : [],
         "type" : {
            "type" : "array",
            "items" : "Identifier"
         }
      },
      {
         "name" : "allele",
         "type" : "string",
         "doc" : "HGVS expression representing the simple allele"
      },
      {
         "name" : "canonicalAlleleIRI",
         "type" : "string",
         "doc" : "The IRI of the CanonicalAllele associated with this SimpleAllele.\n\t\t\n\t\t(cannot use the CanonicalAllele itself until avro supports\n\t\tcircular references)"
      },
      {
         "doc" : "The concrete subtype of SimpleAllele according to the\n\t\tconceptual model (for type-safety when referring to\n\t\tReferenceCoordinates and CanonicalAlleles",
         "type" : "SequenceClass",
         "name" : "sequenceClass"
      },
      {
         "name" : "referenceCoordinate",
         "type" : "ReferenceCoordinate",
         "doc" : "The location of this allele relative to its corresponding\n\t\treference sequence"
      }
   ],
   "type" : "record"
}
```

The IDL format is nice and concise, but can be automatically converted to the JSON format, which would be easier to parse (say, for automatically generating PlantUML input). It does keep track of comments as documentation strings, which is nice, and we could throw Markdown in there for formatting. I'm not sure that we would want to model the ConceptualModel using Avro, though, since it really is most useful as a serialization descriptor.

Anyway, just out there for discussion...

**Comment by tnavatar** [comment]
It’s definitely a thought; I took a peek at this too, it’s a lot less wordy than what I was starting in, which looked a lot like the JSON AVRO schema. The part I have a bit of trouble with is what you mention: it wouldn’t work as well for modeling the conceptual model, since it’s intended to support data serialization, and doesn’t have support for concepts like inheritance, so we’ll probably have to handle that a different way.

**Comment by larrybabb** [comment]
Thanks Bradford for introducing me to AVRO.  I was curious about the format that ga4gh was using but never dug into understanding it.  

I think we need to be careful how tightly we think we will be able to keep our conceptual and resource models in sync.  It is a nice idea to be able to have the attribute definitions transfer, but as we are already seeing the entity definitions are not one-to-one and are truly different in each model.  

While we are having some success with mapping abstract classes in the conceptual model one-to-one with main resource models, I am not confident that will continue indefinitely.  So what I am saying is that I do not think there is a lot of value in trying to reuse definitions across conceptual and resource models.  

I guess, we should consider building out our conceptual model differently if in fact we can use tools like avro and plantuml to generate the resource information.  In the end, I think it is the resource model that will have more utility.  However, I do not want to minimize how important the conceputal model is, because it will provide a starting point for all future changes and allow those that care to see how and why the Resource model was structured as it was.

I'm not sure how helpful this is, but I think I'm very interested in trying to use avro, if we can make even a part of our project better.  And, it would be great to provide representations similar to the ga4gh because they seem to be growing in authority and visibility.  If we can compare or present our models in their form to them, then maybe our work will help influence them and visa versa.

**Comment by tnavatar** [comment]
I do like your suggestion, at a minimum we can represent the resources in a form that’s translatable to AVRO directly.

The message I get, if I understand you correctly Larry, is that the main use of the conceptual model is as an internal tool for developing the structure of the resources, and as a tool to explain to others how this structure came to be (and also as a suggestion for a possible implementation). I feel like the most important representation of the conceptual model is the complete UML diagram, with the layout preserved. A lot of the textual detail about the model in those pages should probably be transferred to the resource pages, and I probably shouldn’t try to build a diagram of that automatically with PlantUML, or any other tool. Let me know if this makes sense, because it definitely changes my approach.

If this works, we’ll have two sections of the model documentation: the conceptual model, which ought to look largely as it does now, and the resource model, which ought to look a lot more like the FHIR documentation. We stick with essentially the workflow that we’ve invented for this model for future models: an initial development phase focused on a diagram in VP, moving a copy of the diagram into GitHub, with enough textual detail to understand the structure of the diagram, with development of the resource side of the model moving into GitHub entirely. We consider the resource model normative and worry less about bringing that level of rigor to the conceptual model once we start work on the resources.

Let me know what you think, this is the direction it seems like we’re headed in for developing a product and a workflow to get there.

**Comment by larrybabb** [comment]
That's precisely what I was suggesting.  Although, I would definitely want everyone on the team to weigh in before making any final decisions.
