### ISSUE TITLE
primary-transcript-region-type not exclusive

### ISSUE THREAD

**Issue by cbizon** [tnavatar/clingen-data-model#64]
The primary transcript reginon type defined here:

http://clingen-data-model.github.io/allele/implementation/value_set_list/primary_transcript_region_type.html

contains values that are not exclusive:

A) exon must be removed.
B) Is there a difference between noncoding exon and psuedogenic exon?  How is it defined?
C) Does the SO term intron include the region denoted by the so term splice-site?  Is there a term for the non-splice site regions of the intron?

As a side note, for these exclusive terms, I think it is important for us to define the situation in which each term is used, rather than just to drop the list of terms.  I seem to recall from our Jan in-person that somebody was going to codify this?

**Comment by srynobio** [comment]
_exon must be removed_
Ultimately I would agree we can do this if we keep the ancillary types, mainly because this is a heavily used feature type and I don't want to create an unnecessary barrier to adoption.

_Is there a difference between noncoding exon and psuedogenic exon? How is it defined?_

| Term | Def |
| --- | --- |
| pseudogenic_exon | A non functional descendant of an exon, part of a pseudogene. |
| noncoding_exon | An exon that does not contain any codons. |

_Does the SO term intron include the region denoted by the so term splice-site? Is there a term for the non-splice site regions of the intron?_

The term splice-site is a child of intron so it's defining the region within an intron, [splice_junction](http://www.sequenceontology.org/browser/current_svn/term/SO:0001902) would include the intron and exon

There is a term: [interior_intron](http://www.sequenceontology.org/browser/current_svn/term/SO:0000191)

**Comment by cbizon** [comment]
OK, we will have the ancillary stuff, and there are lots of good terms to go there.  In terms of the exclusive list, then, it would be:

CDS SO:0000316
interior_intron 
pseudogenic_exon    SO:0000507
splice_site SO:0000162
five_prime_UTR  SO:0000204
three_prime_UTR SO:0000205

noncoding_exon comes out because it overlaps with the UTRs and the psudogenic_exons.

That would cover everything right?  That is assuming that interior_intron means the part of the intron not covered by the intronic splice site.  There's not a definition on the page that I see, so I'm not sure if my assumption is correct.

**Comment by larrybabb** [comment]
When Shawn and Chris come to a consensus on the final "primary" list for the various attributes, we should present them to the larger DMWG.  Is there any chance we could do this for next Wed (4/1/15)?

**Comment by srynobio** [comment]
I'll try to squeeze in time this week and next to get all the types done before Wed.  Maybe by Tue I'll try to finalize the lists.  And we can DMG review them before Wed.

**Comment by cbizon** [comment]
This sounds good.  I did come across one monkey wrench though, which is that we probably need to make the cardinality on this 1..*:

So we've agreed on something like primary region type being a unique value from an exclusive list, with the ancillary version being a nice tagging system.

What what do we do for an allele that spans multiple regions?  So e.g. a deletion that goes from interior_intron, across a splice_site, and into the CDS?

I think that we'd have to put those in an array like:

```
"primaryRegionType": 
[
  "interior_intron",
  "splice_site",
  "CDS"
]
```

Where the list here is understood to mean that the allele spans these primary regions, not that these are different labels for the same primary region.

**Comment by srynobio** [comment]
I think this is a good example of the level of detail annotation someone would want to capture.  I agree with the change in cardinality.

**Comment by srynobio** [comment]
I'm in agreement with the type changes we made, but I think including noncoding_exon maybe needed as it does speak to something different then pseudogenic_exon, not all noncoding exons are pseudogenic  and vise versa.

**Comment by cbizon** [comment]
When would noncoding_exon be used?

**Comment by srynobio** [comment]
After re-thinking this, perhaps non_coding does not have a place when only considering transcript regions.
