### ISSUE TITLE
items of FHIR resources

### ISSUE THREAD

**Issue by ronakypatel** [tnavatar/clingen-data-model#65]
I was looking at the xml schema for gene resource (http://clingen-data-model.github.io/main/resources/clingen-xsd/gene.xsd ) and comparing with example  (http://clingen-data-model.github.io/allele/implementation/examples/G102.html).

I see some properties listed under identifier for gene resource (use, label, system, value). I think this is defined in FHIR identifier resource (not in gene.xsd). Now if I want to have a look at FHIR identifier resource, how shall I get it? This is mainly to define self sufficient model for gene.

**Comment by srynobio** [comment]
I think this is what you want: http://www.hl7.org/implement/standards/fhir/resourcelist.html

But @larrybabb can confirm.

**Comment by larrybabb** [comment]
The most up-to-date FHIR schemas can be downloaded from this page http://hl7-fhir.github.io/.

See the link [FHIR Schemas & Schematrons](http://hl7-fhir.github.io/fhir-all-xsd.zip) in the links under the Implementation heading.

This is a complete zip of all schemas, but you should see a base schema and/or a datatypes schema that should help with the datatypes like "Identifier" and "Codeableconcept".  

Be warned that you (or we) will need to make some decisions on where to truncate the schema so that we don't get into the "Extension" support which is baked into every "Resource" which everything is based on.  I am also not sure we should recreate all of the attributes and types for every datatype for our isolated version of a model.

Maybe the DMWG should add a discussion point on our agenda for next Tuesday to figure out how to proceed.  We need to be careful about saying we are building on top of FHIR and then make things completely custom with the appearance that is using FHIR specifications.

**Comment by larrybabb** [comment]
Review implementation of CodeableConcept with the Allele Registry project.

Add documentation to this project to clarify relationship between our "specification" and FHIR's.
