### ISSUE TITLE
display on reference sequence?

### ISSUE THREAD

**Issue by cbizon** [tnavatar/clingen-data-model#69]
In our SimpleAllele resource model, we have something like this (JSON):

```
"referenceSequence": 
    {
      "reference": "/ReferenceSequence/RS201",
      "display": "NM_001014794.2"
    },
```

That is, for a reference sequence, we have a node that contains both the lookup id for the reference sequence, as well as a display name.

Do we really want this?   Why is the display name up to the simple allele?  Can it change?  

I know why it is there of course: to keep a client from having to go look up the info.  Not sure that is a good idea or not...

One other possibility would be to use the accessions as part of the clingen id for this thing, so then it would be something like:

```
"referenceSequence":"http://clingendb.clingen.org/ReferenceSequence/NM_001014794.2"
```

But that might get confusing if we have e.g. both NCBI and ensemble things in the same db.

**Comment by larrybabb** [comment]
Remember, that our referencesequence resources are not providing a mechanism to represent two or more equivalent reference sequences as a single resource instance.  And, a simpleAllele is a very specific representation on a very specific reference sequence.  So if you had ensemble and ncbi refseqs and wanted to show the same canonical allele on each one, then you would have to create two different simple alleles (even if the only difference was the ncbi refseq vs the ensemble refseq).  

The display attribute is an optional (convenience thing I think) provided for in the FHIR spec (I could be making that up?).  Anyway, it is a way to provide a human readable value so that you do not have to bundle the referenced resource in the message when an identifier works.  

Here's the formal FHIR description of [Reference.display](http://hl7-fhir.github.io/references-definitions.html#Reference.display) all related resources in a message use the Reference datatype to pass the Reference.reference ("Relative, internal or absolute URL reference") and Reference.display ("Text alternative for the resource").

We can drop it from the examples if you want.  But I'm not sure we want to deviate from the FHIR definition of the structure.  I think it is a slippery slope if we break ties with the notion that our models are based on the FHIR spec.  We will have a lot more technical work which will most definitely derail us from our goals and create considerable risk to our success.

**Comment by cbizon** [comment]
Yes, I agree on the NCBI/ensembl stuff.  I was making a slightly different point there, but not one that matters very much.

The main point was just whining that the FHIR JSON is not very idiomatic for JSON-LD.  But I do think that if our goal is to match FHIR structure, then the non-idiomatic (but correct) JSON-LD is simply the cost of doing business.

I'm going to keep going following the FHIR-type implementations.
