### ISSUE TITLE
How should SimpleAminoAcidCanonicalAlleles be canonicalized?

### ISSUE THREAD

**Issue by bpow** [tnavatar/clingen-data-model#84]
@cbizon has a question on the SimpleAminoAcidCanonicalAllele page, which I don't know if the larger group had decided on yet. There are three levels of potential canonicalization: 

SimpleAminoAcidAlleles could potentially be aggregated when they are:  
- in different versions of the same AminoAcidReferenceSequence.  
- in different AminoAcidReferenceSequences from the same public database, as long as their associated TranscriptReferenceSequence maps to the same Gene
- in different AminoAcidReferenceSequences from different public databases, as long as their associated TranscriptReferenceSequence maps to the same gene.

Is this something we should specify, or leave up to the implementer of a specific canonicalization?

**Comment by larrybabb** [comment]
Since the phrase "potential canonicalization" is used to qualify the
possibilities I think it is good to leave them in.  You may state,
additionally, that the rules for canonicalizing may differ from
implementation to implementation but the concept of canonicalization is
inherent in these models due to the variety in sources of similar and/or
overlapping public reference sequences used as a basis for identifying
alleles, whether they be amino acid or nucleotide alleles.

From:  Bradford Powell notifications@github.com
Reply-To:  tnavatar/clingen-data-model
<reply+000ea21b018369f9db23987e7b88ee725762dab8b3c8a88492cf000000011142dc019
2a169ce040d51a2@reply.github.com>
Date:  Sunday, April 12, 2015 9:21 PM
To:  tnavatar/clingen-data-model clingen-data-model@noreply.github.com
Subject:  [clingen-data-model] How should SimpleAminoAcidCanonicalAlleles be
canonicalized? (#84)

@cbizon https://github.com/cbizon  has a question on the
SimpleAminoAcidCanonicalAllele page, which I don't know if the larger group
had decided on yet. There are three levels of potential canonicalization:

SimpleAminoAcidAlleles could potentially be aggregated when they are:
- in different versions of the same AminoAcidReferenceSequence.
- 
- in different AminoAcidReferenceSequences from the same public database, as
  long as their associated TranscriptReferenceSequence maps to the same Gene
- in different AminoAcidReferenceSequences from different public databases,
  as long as their associated TranscriptReferenceSequence maps to the same
  gene.
  Is this something we should specify, or leave up to the implementer of a
  specific canonicalization?


Reply to this email directly or view it on GitHub
https://github.com/tnavatar/clingen-data-model/issues/84 .
